### ISSUE TITLE
Funcionamiento Sidebar

### ISSUE THREAD

**Issue by lugezz** [lumato92/Proyecto_CaC_Django#15]
# Funcionamiento Sidebar

Ver que por momentos el Sidebar tapa el contenido del cuerpo de la página.

Aquí muestro en un video

https://user-images.githubusercontent.com/41469771/198287971-ccf71ef2-35e6-453a-b796-3202bf923a84.mp4

**Comment by lumato92** [comment]
Se soluciono el comportamiento del sidebar agregando el archivo js del template , sin embargo cuando se hace click en el hamburger button para achicar la sidebar y luego se le hace un hover la misma se expande tapando parte del contenido, esta falla viene heredada del template

**Comment by lumato92** [comment]
https://user-images.githubusercontent.com/55516181/199098280-02aae849-2c2e-4e1f-af72-5d9fcf3a51f3.mp4
